#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
;SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
;SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
;OnMessage(0x201, "WM_LBUTTONDOWN")

Home:
Gui, Home:Add, Text, x2 y9 w130 h20 +BackgroundTrans, Location - Route/Town:
Gui, Home:Add, Edit, x2 y20 w200 h20 vTown gCheck, 
Gui, Home:Add, Text, x0 y45 w210 h20 +BackgroundTrans, Pokemon - Time - Rarity - Lvl:
Gui, Home:Add, Edit, x0 y60 w130 h20 vPokemon1, Pokemon1
Gui, Home:Add, Edit, x130 y60 w130 h20 vPokemonTime1, PokemonTime1
Gui, Home:Add, Edit, x260 y60 w130 h20 +BackgroundTrans vPokemonRare1, Pokemon Rarity
Gui, Home:Add, Edit, x390 y60 w85 h20 vPokemonLvl1, 100
Gui, Home:Add, Edit, x0 y80 w130 h20 vPokemon2, Pokemon2
Gui, Home:Add, Edit, x130 y80 w130 h20 vPokemonTime2, PokemonTime2
Gui, Home:Add, Edit, x260 y80 w130 h20, Edit
Gui, Home:Add, Edit, x0 y100 w130 h20 vPokemon3, Pokemon3
Gui, Home:Add, Edit, x130 y100 w130 h20 vPokemonTime3, PokemonTime3
Gui, Home:Add, Edit, x0 y120 w130 h20 vPokemon4, Pokemon4
Gui, Home:Add, Edit, x130 y120 w130 h20 vPokemonTime4, PokemonTime4
Gui, Home:Add, Edit, x260 y160 w130 h20, Edit
Gui, Home:Add, Edit, x260 y100 w130 h20, Edit
Gui, Home:Add, Edit, x260 y120 w130 h20, Edit
Gui, Home:Add, Edit, x0 y140 w130 h20 vPokemon5, Pokemon5
Gui, Home:Add, Edit, x130 y140 w130 h20 vPokemonTime5, PokemonTime5
Gui, Home:Add, Edit, x260 y140 w130 h20, Edit
Gui, Home:Add, Edit, x0 y160 w130 h20 vPokemon6, Pokemon6
Gui, Home:Add, Edit, x130 y160 w130 h20 vPokemonTime6, PokemonTime6
Gui, Home:Add, Edit, x0 y180 w130 h20 vPokemon7, Pokemon7
Gui, Home:Add, Edit, x130 y180 w130 h20 vPokemonTime7, PokemonTime7
Gui, Home:Add, Edit, x260 y180 w130 h20, Edit
Gui, Home:Add, Edit, x0 y200 w130 h20 vPokemon8, Pokemon8
Gui, Home:Add, Edit, x130 y200 w130 h20 vPokemonTime8, PokemonTime8
Gui, Home:Add, Edit, x260 y200 w130 h20, Edit
Gui, Home:Add, Edit, x0 y220 w130 h20 vPokemon9, Pokemon9
Gui, Home:Add, Edit, x130 y220 w130 h20 vPokemonTime9, PokemonTime9
Gui, Home:Add, Edit, x260 y220 w130 h20, Edit
Gui, Home:Add, Edit, x390 y80 w85 h20, 100
Gui, Home:Add, Edit, x390 y100 w85 h20, 100
Gui, Home:Add, Edit, x390 y120 w85 h20, 100
Gui, Home:Add, Edit, x390 y140 w85 h20, 100
Gui, Home:Add, Edit, x390 y160 w85 h20, 100
Gui, Home:Add, Edit, x390 y180 w85 h20, 100
Gui, Home:Add, Edit, x390 y200 w85 h20, 100
Gui, Home:Add, Edit, x390 y220 w85 h20, 100
Gui, Home:Add, Text, x0 y250 w490 h20 +BackgroundTrans disabled, -V0.1--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Gui, Home:Add, Picture, x420 y5 w48 h48 glike, %A_WorkingDir%/custom/feedback.png
Gui, Home:Add, Text, x305 y30 w105 h15, Like ------------------------>
Gui, Home:Show, w478 h267, PokeMMO Encounter Locator
return

HomeGuiClose:
ExitApp
; This Gui is generated by X-GUI Creator

;Gui, Home: -Caption
;Gui, Home:Add, Picture, x0 y-40 w480 h600, %A_WorkingDir%/custom/custom.png


like:
Run, https://pokemmo.com
return


Check:
Gui,Home:Submit,NoHide
{
	if (Town = "Pallet") or (Town = "Pallet Town"){
		GuiControl,Home:,Pokemon1,Pdgey
		GuiControl,Home:,PokemonTime1,Always
		GuiControl,Home:,PokemonRare1,Very Common
		GuiControl,Home:,Pokemonlvl1,2-5
	}
	else
		if (Town = "") or (Town = ""){
			GuiControl,Home:,Pokemon1,
			GuiControl,Home:,PokemonTime1,
			GuiControl,Home:,PokemonRare1,
			GuiControl,Home:,Pokemonlvl1,
		}
}
return




;WM_LBUTTONDOWN()
;{
;	PostMessage, 0xA1, 2
;	return
;}